{% set version = '0.3-9' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-clustmixtype
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/clustMixType_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/clustMixType/clustMixType_{{ version }}.tar.gz
  sha256: a237359f566abdd01cc9ca3056bc83b0f77b189a9f4e4a8586ac94e51bb55146

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcolorbrewer
    - r-tibble
  run:
    - r-base
    - r-rcolorbrewer
    - r-tibble

test:
  commands:
    - $R -e "library('clustMixType')"           # [not win]
    - "\"%R%\" -e \"library('clustMixType')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=clustMixType
  license: GPL-2.0-or-later
  summary: 'Functions to perform k-prototypes partitioning clustering for mixed variable-type
    data according to Z.Huang (1998): Extensions to the k-Means Algorithm for Clustering
    Large Data Sets with Categorical Variables, Data Mining and Knowledge Discovery
    2, 283-304.'
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: clustMixType
# Version: 0.3-9
# Date: 2022-12-13
# Title: k-Prototypes Clustering for Mixed Variable-Type Data
# Author: Gero Szepannek [aut, cre], Rabea Aschenbruck [aut]
# Maintainer: Gero Szepannek <gero.szepannek@web.de>
# Imports: RColorBrewer, tibble
# Suggests: testthat
# Description: Functions to perform k-prototypes partitioning clustering for mixed variable-type data according to Z.Huang (1998): Extensions to the k-Means Algorithm for Clustering Large Data Sets with Categorical Variables, Data Mining and Knowledge Discovery 2, 283-304.
# License: GPL (>= 2)
# RoxygenNote: 7.2.0
# NeedsCompilation: no
# Packaged: 2022-12-13 18:18:19 UTC; szepannek
# Encoding: UTF-8
# Repository: CRAN
# Date/Publication: 2022-12-14 19:50:02 UTC
